import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import DashboardLayout from "./components/layout/DashboardLayout";

// Use Inter from Google Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Custom Font: Grandis Extended
const grandisExtended = localFont({
  src: [
    {
      path: "../public/fonts/GrandisExtended-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/GrandisExtended-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-grandis",
  display: "swap",
});

export const metadata = {
  title: "Nexchat",
  description: "Generated by Nexchat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${grandisExtended.variable} antialiased`}
      >
        <DashboardLayout>
          {children}
        </DashboardLayout>
      </body>
    </html>
  );
}
